### ISSUE TITLE
Website to search for streets and their meaning

### ISSUE THREAD

**Issue by metaodi** [EqualStreetNames/equalstreetnames-zurich#3]
Today I learned about this website by the Stadtarchiv of the City of Zurich: https://www.stadt-zuerich.ch/prd/de/index/stadtarchiv/strassennamen.html#

It has a search bar and returns the meaning of a street name including persons. If you add entries manually this page is super helpful instead of digging through the street names dataset.

Not sure if you want to update the instructions in the README, but though I'll leave a note here.

**Comment by CaptainInler** [comment]
Hi @metaodi Thanks a lot for your message and the link to the StrassennamenDatenbank. We actually created for our workinggroup a spreadsheet who is requesting the [Strassennamen WFS](https://data.stadt-zuerich.ch/dataset/geo_strassennamenverzeichnis/resource/098a1493-15ba-4fa5-806c-bb7dc27ea0e7) and filters for Streets named after a Person.
You are right, I should update the Readme and put that list online for everyone who wants to help :sweat_smile:

**Comment by CaptainInler** [comment]
@metaodi [README](https://github.com/EqualStreetNames/equalstreetnames-zurich/blob/master/README.md) is now up to date

**Comment by metaodi** [comment]
Thanks @CaptainInler 

I build a little overview on my own: https://equalstreetnames-zurich-todo.herokuapp.com/ (code: https://github.com/metaodi/equalstreetnames-zurich-todo) to find all OSM entries that are potentially linked to a person, but do not have a `name:etymology:wikidata` tag.
